### PR TITLE
fix travis. move to xctool

### PR DESCRIPTION
**Pull request by kostiakoval**
travis fix. not working with xcpretty :(

### CODE REVIEW

**Comment by 3lvis** [comment]
Can you remove the commented text?

**Comment by 3lvis** [comment]
You can run the command locally for faster feedback

**Comment by kostiakoval** [comment]
I did it works

**Comment by 3lvis** [comment]
Try cocoapod update, Travis version is old

**Comment by kostiakoval** [comment]
screen shot 2015-03-11 at 16 31 41

**Comment by kostiakoval** [comment]
`podfile: Tests/Podfile` hope this was it

**Comment by 3lvis** [comment]
I'll try

**Comment by kostiakoval** [comment]
last try

**Comment by 3lvis** [comment]
@kostiakoval https://github.com/hyperoslo/NSArray-HYPFind/pull/5

**Pull request merged**
